[changelog]
header = ""
body = """
## [{{ version | trim_start_matches(pat="v") }}] - {{ date | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{commit.scope}}**: {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "Added"},
    { message = "^fix", group = "Fixed"},
    { message = "^doc", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Changed"},
    { message = "^style", group = "Style"},
    { message = "^test", group = "Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^chore", group = "Changed"},
]
tag_pattern = "v[0-9]*"
ignore_tags = ""