# Docker Compose configuration for running netscan in a containerized environment
# This extends the existing docker-compose.yml which provides InfluxDB

services:
  # netscan service - network monitoring application
  netscan:
    # Use the GitHub Container Registry image (replace 'latest' with specific version for production)
    image: ghcr.io/extkljajicm/netscan:latest
    container_name: netscan
    restart: unless-stopped
    
    # Network mode: host allows netscan to access the host network for ICMP and SNMP
    network_mode: host
    
    # Add Linux capability for raw socket access (ICMP ping)
    cap_add:
      - NET_RAW
    
    # Mount config file and environment variables
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./logs:/app/logs
    
    # Environment variables for sensitive configuration
    # These override values in config.yml
    environment:
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-netscan-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-test-org}
      - SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}
    
    # Ensure InfluxDB is started first
    depends_on:
      influxdb:
        condition: service_healthy
    
    # Resource limits (adjust based on network size)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # InfluxDB service (from original docker-compose.yml)
  influxdb:
    image: influxdb:2.7
    container_name: influxdbv2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_BUCKET=netscan
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=netscan-token
    volumes:
      - influxdbv2-data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  influxdbv2-data:
