version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdbv2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_BUCKET=netscan
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=netscan-token
    volumes:
      - influxdbv2-data:/var/lib/influxdb2
volumes:
  influxdbv2-data:
